{ pkgs, ... }:
{
  environment = {
    systemPackages = with pkgs; [
      kdePackages.audiotube
      kdePackages.baloo-widgets
      kdePackages.dolphin
      kdePackages.dolphin-plugins
      kdePackages.ffmpegthumbs
      kdePackages.filelight
      kdePackages.gwenview
      kdePackages.isoimagewriter
      kdePackages.kamoso
      kdePackages.kbackup
      kdePackages.kcalc
      kdePackages.kcachegrind
      kdePackages.kcharselect
      kdePackages.kcolorchooser
      kdePackages.kcron
      kdePackages.kdegraphics-thumbnailers
      kdePackages.kdenetwork-filesharing
      kdePackages.kdf
      kdePackages.kfind
      kdePackages.kgpg
      kdePackages.kjournald
      kdePackages.kmix
      kdePackages.koko
      kdePackages.kompare
      kdePackages.konsole
      kdePackages.krdc
      kdePackages.krdp
      kdePackages.ktorrent
      kdePackages.ksystemlog
      kdePackages.iio-sensor-proxy
      kdePackages.merkuro
      kdePackages.okular
      kdePackages.partitionmanager
      kdePackages.qtstyleplugin-kvantum
      kdePackages.sweeper
      kdePackages.yakuake
      ark
      heaptrack
      ffmpegthumbnailer
      graphviz
      icoextract
      icoutils
      kdiff3
      kdiskmark
      krename
      krita
      krusader
      maliit-keyboard
      okteta
      ulauncher
    ];
  };
}
