[
  "--set-str DEFAULT_HOSTNAME v7w7r"
  "--set-str DEFAULT_NET_SCH fq"
  "--set-str DEFAULT_TCP_CONG bbr"

  "--set-val HZ 300"
  "--set-val NR_CPUS 8"

  "-e CRYPTO_ZSTD"
  "-e DRM_LIMA"
  "-e DRM_SUN4I"
  "-e F2FS_FS"
  "-e DEFAULT_BBR"
  "-e DEFAULT_FQ"
  "-e NO_HZ"
  "-e NO_HZ_COMMON"
  "-e NO_HZ_IDLE"
  "-e PREEMPT_NONE"
  "-e PREEMPT_NONE_BUILD"

  "-e ZRAM_DEF_COMP_LZ4"
  "-e ZRAM_LZ4_COMPRESS"

  "-m NET_SCH_FQ_CODEL"
  "-m KVM"
  "-m SUNXI_ADDR_MGT"
  "-m SPRDWL_NG"
  "-m TTY_OVERY_SDIO"
  "-m TCP_CONG_CUBIC"
  "-m VIRTIO"
  "-m ZRAM"

  "-d ACCESSIBILITY"
  "-d AW_WIFI_DEVICE_UWE5622"
  "-d DEBUG_FS"
  "-d DRM_RADEON"
  "-d KEXEC"
  "-d KEXEC_JUMP"
  "-d INPUT_JOYSTICK"
  "-d INPUT_TABLET"
  "-d INPUT_TOUCHSCREEN"
  "-d KALLSYMS_ALL"
  "-d HZ_1000"
  "-d NO_HZ_FULL"
  "-d NTSYNC"
  "-d PREEMPT"
  "-d PREEMPT_DYNAMIC"
  "-d PREEMPT_LAZY"
  "-d PREEMPTION"
  "-d PREEMPT_VOLUNTARY"
  "-d PROFILING"
  "-d SECURITY_SELINUX"
  "-d SECURITY_TOMOYO"

  "-d SOUND"
  "-d SND"
  "-d SND_SOC"
  "-d SND_SUN4I_CODEC"
  "-d STAGING"
  "-d SPARD_WLAN_SUPPORT"
  "-d WLAN_VENDOR_ATH"
  "-d WLAN_VENDOR_BROADCOM"
  "-d WLAN_VENDOR_INTEL"
  "-d WLAN_VENDOR_MARVELL"
  "-d WLAN_VENDOR_TI"
  "-d WLAN_UWE5622"
  "-d WATCHDOG"
  "-d ZRAM_BACKEND_842"
]
++ (import ../config/develop.nix)
++ (import ../config/vendors.nix)
