{
  inputs,
  lib,
  kernel,
  kernel-versions,
  ...
}:
{
  flake-file.inputs.bunker-patches = {
    url = "github:amaanq/bunker-patches";
    flake = false;
  };

  kernel.patches.bunker = {
    common = { }: [
      "bunker/0006-enable-kstack_erase-by-default"
      "bunker/0008-disable-proc_kcore-by-default"
      "clear/0001-net-dst-reduce-false-sharing-in-dst_entry"
      "clear/0009-mm-compaction-increase-proactive-compaction-check-in"
      "grapheneos/0001-disable-ldisc_autoload-by-default"
      "grapheneos/0004-disable-memory_hotplug-by-default"
      "xanmod/0003-block-set-rq_affinity-to-force-complete-I-O-on-same-"
      "xanmod/0004-block-mq-deadline-disable-front_merges-by-default"
      "xanmod/0005-block-mq-deadline-increase-write-priority-to-improve"
      "xanmod/0006-vfs-decrease-rate-at-which-caches-are-reclaimed"
      "xanmod/0008-wait-allow-__wake_up_pollfree-from-GPL-modules"
      "xanmod/0009-file-export-file_close_fd-for-GPL-modules"
      "xanmod/0010-binder-give-binder_alloc-its-own-debug-mask-file"
      "xanmod/0011-binder-turn-into-loadable-module"
      "xanmod/0012-tcp-add-sysctl-to-skip-collapse-when-receive-buffer-"
      "xanmod/0014-dm-crypt-Disable-workqueues-for-crypto-ops"
      "zen/0009-mm-set-default-max-map-count-to-INT_MAX-5"
    ];

    latest =
      {
        isVanilla ? true,
      }:
      (
        map
          (
            patch:
            "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.latest}/${patch}.patch"
          )
          [
            "bunker/0003-rust-allow-clang-native-randstruct-configs"
            "bunker/0007-enable-page_table_check_enforced-by-default"
            "bunker/0010-rust-add-backlight-device-abstraction"
            "clear/0006-init-reduce-default-timer-slack-to-50ns"
            "cachyos/0004-sched-ext"
            "cachyos/0010-block-reduce-BFQ-and-mq-deadline-lock-contention"
            "cachyos/0013-mm-add-missing-extern-declarations-for-le9-workingse"
            "cachyos/0014-x86-cpu-bugs-VMSCAPE-BHB-clear-mitigation"
            "cachyos/0018-drivers-net-add-Realtek-R8125-R8126-5GbE-driver"
            "xanmod/0001-sched-fair-set-tunable-latencies-to-unscaled"
            "xanmod/0007-locking-rwsem-spin-more-aggressively-before-cpu_rela"
            "zen/0006-cpufreq-remove-schedutil-dependency-on-Intel-AMD-P-S"
          ]
        ++ (map (
          patch:
          "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.latest}/${patch}.patch"
        ) (kernel.patches.bunker.common { }))
        ++ (lib.optionals isVanilla (
          map
            (
              patch:
              "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.latest}/${patch}.patch"
            )
            [
              "bunker/0001-init-add-CONFIG_BUNKER-base-config-item"
              "bunker/0004-enable-randstruct_full-by-default"
              "bunker/0005-mm-increase-VM_READAHEAD_PAGES-to-2MB"
              "bunker/0009-i2c-add-nct6775-smbus-driver-for-openrgb"
              "bunker/0013-r8125-disable-proc-debug-files"
              "bunker/0014-block-adios-fix-clzll-and-cache-names"
              "bunker/0015-pci-intel-nvme-remap-null-check"
              "bunker/0017-sched-fair-fix-is_idle_core-stub-arity-for-SCHED_SMT"
              "cachyos/0001-tcp-bbr3-add-BBRv3-congestion-control"
              "cachyos/0002-fixes-inline-sched-mm-tick-vtime-rcu-quirks"
              "cachyos/0006-block-add-ADIOS-Adaptive-Deadline-I-O-Scheduler"
              "cachyos/0007-mm-add-le9-working-set-protection"
              "cachyos/0008-media-add-v4l2loopback-virtual-video-device"
              "cachyos/0009-mm-add-Kconfig-defaults-for-compaction-and-dirty-pag"
              "cachyos/0012-sched-add-Piece-Of-Cake-fast-idle-CPU-selector"
              "cachyos/0015-drm-VESA-DSC-BPP-pass-through-timings"
              "cachyos/0016-kbuild-Add-Clang-Polly-polyhedral-loop-optimizer"
              "cachyos/0017-kbuild-dkms-clang-compatibility"
              "cachyos/0019-cpuidle-prefer-teo-over-menu-governor"
              "cachyos/0020-media-v4l2loopback-update-to-0.15.4"
              "clear/0002-tcp-raise-per-socket-write-memory-limit-to-16MB"
              "clear/0003-net-sock-increase-_SK_MEM_PACKETS-to-1024"
              "clear/0004-net-sock-batch-socket-memory-reclaim-in-sk_mem_uncha"
              "clear/0005-sched-fair-remove-upper-limit-on-cpu-number"
              "clear/0006-init-reduce-default-timer-slack-to-50ns"
              "clear/0007-exit-use-mmput_async-to-reduce-exit-latency"
              "clear/0008-memcg-increase-MEMCG_CHARGE_BATCH-to-128"
              "clear/0010-sched-core-add-branch-hints-based-on-gcov-analysis"
              "clear/0011-readdir-add-unlikely-branch-hint-on-len-check"
              "clear/0012-pci-increase-PME-check-interval-to-4-seconds"
              "xanmod/0001-sched-fair-set-tunable-latencies-to-unscaled"
              "xanmod/0002-sched-add-yield_type-sysctl-to-reduce-or-disable-sch"
              "xanmod/0007-locking-rwsem-spin-more-aggressively-before-cpu_rela"
              "zen/0001-PCI-add-ACS-override-support"
              "zen/0004-drivers-initialize-ata-before-graphics"
              "zen/0005-input-evdev-use-call_rcu-when-detaching-client"
              "zen/0010-mm-stop-kswapd-early-when-nothing-s-waiting-for-it-t"
              "zen/0011-ahci-disable-staggered-spinup-by-default"
              "zen/0012-kernel-Kconfig.preempt-remove-EXPERT-conditional-on-"
              "zen/0013-block-use-BFQ-as-the-elevator-for-SQ-devices"
              "zen/0014-block-Clean-up-elevator_set_default"
              "zen/0015-mm-enable-background-reclaim-of-hugepages"
              "zen/0016-sched-eevdf-tune-for-interactivity"
              "zen/0017-mm-disable-unevictable-compaction"
              "zen/0018-mm-disable-watermark-boosting-by-default"
              "zen/0019-mm-swap-disable-swap-in-readahead"
              "zen/0020-block-use-Kyber-as-the-elevator-for-MQ-devices"
            ]
        ))
      )
      |> lib.sort lib.lessThan;

    lts =
      {
        isVanilla ? true,
        isHardened ? false,
      }:
      (
        map
          (
            patch:
            "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.lts}/${patch}.patch"
          )
          [
            "cachyos/0017-mm-add-missing-extern-declarations-for-le9-workingse"
            "cachyos/0018-x86-cpu-bugs-VMSCAPE-BHB-clear-mitigation"
            "cachyos/0019-drm-VESA-DSC-BPP-pass-through-timings"
            "cachyos/0022-drivers-net-add-Realtek-R8125-R8126-5GbE-driver"
            "cachyos/0023-cpuidle-prefer-teo-over-menu-governor"
            "clear/0010-sched-core-add-branch-hints-based-on-gcov-analysis"
            "clear/0012-pci-increase-PME-check-interval-to-4-seconds"
            "upstream/0002-time-timecounter-inline-timecounter_cyc2time"
            "upstream/0003-x86-lib-inline-csum_ipv6_magic"
            "upstream/0004-x86-apic-inline-x2apic_send_IPI_dest"
            "upstream/0005-cpuidle-menu-remove-incorrect-unlikely-annotation"
            "upstream/0007-tcp-inline-tcp_filter"
            "upstream/0008-ipv6-optimize-fl6_update_dst"
            "upstream/0009-net_sched-sch_fq-rework-fq_gc-to-avoid-stack-canary"
            "upstream/0010-tcp-use-__skb_push-in-__tcp_transmit_skb"
            "upstream/0011-ipv6-do-not-use-skb_header_pointer-in-icmpv6_filter"
            "upstream/0012-tcp-split-tcp_check_space-in-two-parts"
            "upstream/0015-btf-optimize-type-lookup-with-binary-search"
            "upstream/0016-btf-verify-btf-sorting"
            "upstream/0019-mount-add-OPEN_TREE_NAMESPACE"
            "xanmod/0015-kbuild-add-sms-based-software-pipelining-flags"
          ]
        ++ (map (
          patch:
          "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.lts}/${patch}.patch"
        ) (kernel.patches.bunker.common { }))
        ++ (lib.optionals isVanilla (
          map
            (
              patch:
              "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.latest}/${patch}.patch"
            )
            [
              "bunker/0004-enable-randstruct_full-by-default"
              "bunker/0005-mm-increase-VM_READAHEAD_PAGES-to-2MB"
              "bunker/0007-enable-page_table_check_enforced-by-default"
              "cachyos/0002-sched-Make-raw_spin_rq_unlock-inline"
              "cachyos/0003-sched-core-Make-finish_task_switch-and-its-subfuncti"
              "cachyos/0004-tcp-bbr3-add-BBRv3-congestion-control"
              "cachyos/0006-sched-ext"
              "cachyos/0008-bluetooth-btusb-add-device-quirk"
              "cachyos/0010-block-add-ADIOS-Adaptive-Deadline-I-O-Scheduler"
              "cachyos/0011-mm-add-le9-working-set-protection"
              "cachyos/0012-media-add-v4l2loopback-virtual-video-device"
              "cachyos/0013-mm-add-Kconfig-defaults-for-compaction-and-dirty-pag"
              "cachyos/0014-block-reduce-BFQ-and-mq-deadline-lock-contention"
              "cachyos/0016-sched-add-Piece-Of-Cake-fast-idle-CPU-selector"
              "cachyos/0020-kbuild-Add-Clang-Polly-polyhedral-loop-optimizer"
              "cachyos/0021-kbuild-dkms-clang-compatibility"
              "cachyos/0024-crypto"
              "clear/0002-tcp-raise-per-socket-write-memory-limit-to-16MB"
              "clear/0003-net-sock-increase-_SK_MEM_PACKETS-to-1024"
              "clear/0004-net-sock-batch-socket-memory-reclaim-in-sk_mem_uncha"
              "clear/0005-sched-fair-remove-upper-limit-on-cpu-number"
              "clear/0006-init-reduce-default-timer-slack-to-50ns"
              "clear/0007-exit-use-mmput_async-to-reduce-exit-latency"
              "clear/0008-memcg-increase-MEMCG_CHARGE_BATCH-to-128"
              "clear/0010-sched-core-add-branch-hints-based-on-gcov-analysis"
              "clear/0011-readdir-add-unlikely-branch-hint-on-len-check"
              "clear/0012-pci-increase-PME-check-interval-to-4-seconds"
              "upstream/0001-drm-amdgpu-don-t-attach-the-tlb-fence-for-SI"
              "upstream/0006-cpuidle-menu-always-check-timers-with-tick-stopped"
              "upstream/0013-inet-RAW-sockets-using-IPPROTO_RAW-MUST-drop-incomin"
              "upstream/0017-slab-introduce-kmalloc_obj-and-family"
              "upstream/0018-slab-introduce-kmalloc_flex-and-family"
              "xanmod/0001-sched-fair-set-tunable-latencies-to-unscaled"
              "xanmod/0002-sched-add-yield_type-sysctl-to-reduce-or-disable-sch"
              "xanmod/0007-locking-rwsem-spin-more-aggressively-before-cpu_rela"
              "xanmod/0013-sched-wait-Do-accept-in-LIFO-order-for-cache-efficie"
              "xanmod/0015-kbuild-add-sms-based-software-pipelining-flags"
              "zen/0001-PCI-add-ACS-override-support"
              "zen/0002-PCI-add-Intel-remapped-NVMe-device-support"
              "zen/0004-drivers-initialize-ata-before-graphics"
              "zen/0005-input-evdev-use-call_rcu-when-detaching-client"
              "zen/0010-mm-stop-kswapd-early-when-nothing-s-waiting-for-it-t"
              "zen/0011-ahci-disable-staggered-spinup-by-default"
              "zen/0012-kernel-Kconfig.preempt-remove-EXPERT-conditional-on-"
              "zen/0013-block-use-BFQ-as-the-elevator-for-SQ-devices"
              "zen/0014-block-Clean-up-elevator_set_default"
              "zen/0015-mm-enable-background-reclaim-of-hugepages"
              "zen/0016-sched-eevdf-tune-for-interactivity"
              "zen/0017-mm-disable-unevictable-compaction"
              "zen/0018-mm-disable-watermark-boosting-by-default"
              "zen/0019-mm-swap-disable-swap-in-readahead"
            ]
        ))
        ++ (lib.optionals isHardened (
          map
            (
              patch:
              "${inputs.bunker-patches}/patches/${lib.versions.majorMinor kernel-versions.latest}/hardened/${patch}.patch"
            )
            [
              "0001-add-sysctl-to-allow-disabling-unprivileged-CLONE_NEW"
              "0002-security-add-config-for-default-of-unprivileged_user"
              "0003-make-default_mmap_min_addr-match-lsm_mmap_min_addr"
              "0004-enable-hardened_usercopy-by-default"
              "0005-enable-security_dmesg_restrict-by-default"
              "0006-set-kptr_restrict-2-by-default"
              "0007-enable-list_hardened-by-default"
              "0008-enable-bug_on_data_corruption-by-default"
              "0009-enable-slab_freelist_random-by-default"
              "0010-enable-slab_freelist_hardened-by-default"
              "0011-disable-slab_merge_default-by-default"
              "0012-enable-fortify_source-by-default"
              "0013-enable-panic_on_oops-by-default"
              "0014-stop-hiding-slub_debug-behind-expert"
              "0015-stop-hiding-x86_16bit-behind-expert"
              "0016-disable-x86_16bit-by-default"
              "0017-stop-hiding-modify_ldt_syscall-behind-expert"
              "0018-disable-modify_ldt_syscall-by-default"
              "0019-set-legacy_vsyscall_none-by-default"
              "0020-stop-hiding-aio-behind-expert"
              "0021-disable-aio-by-default"
              "0022-disable-devport-by-default"
              "0023-disable-proc_vmcore-by-default"
              "0024-disable-nfs_debug-by-default"
              "0025-enable-debug_wx-by-default"
              "0026-disable-legacy_ptys-by-default"
              "0027-disable-devmem-by-default"
              "0028-enable-io_strict_devmem-by-default"
              "0029-disable-compat_brk-by-default"
              "0030-use-maximum-supported-mmap-rnd-entropy-by-default"
              "0031-enable-protected_-symlinks-hardlinks-by-default"
              "0032-enable-security-by-default"
              "0033-enable-security_yama-by-default"
              "0034-enable-security_network-by-default"
              "0035-enable-audit-by-default"
              "0036-enable-security_selinux-by-default"
              "0037-enable-syn_cookies-by-default"
              "0038-enable-init_on_alloc_default_on-by-default"
              "0039-enable-init_on_free_default_on-by-default"
              "0040-kconfig-select-debug_fs_allow_none-by-default-if-debug_fs-is"
              "0041-stop-hiding-uid16-behind-expert"
              "0042-disable-uid16-by-default"
              "0043-kconfig-enable-randomize_kstack_offset_default-by-default"
              "0044-kconfig-disable-legacy_tiocsti-by-default"
              "0045-mm-slab-enable-random_kmalloc_caches-by-default"
              "0046-kconfig-enable-mseal_system_mappings-by-default"
              "0047-add-__read_only-for-non-init-related-usage"
              "0048-mark-slub-runtime-configuration-as-__ro_after_init"
              "0049-add-__ro_after_init-to-slab_nomerge-and-slab_state"
              "0050-mark-kmem_cache-as-__ro_after_init"
              "0051-mark-__-supported-default_kernel-_pte_mask-as-__ro_after_ini"
              "0052-mark-kobj_ns_type_register-as-only-used-for-init"
              "0053-mark-open_softirq-as-only-used-for-init"
              "0054-mark-softirq_vec-as-__ro_after_init"
              "0055-slub-add-multi-purpose-random-canaries"
              "0056-slub-add-support-for-verifying-slab-sanitization"
              "0057-slub-extend-init_on_free-to-slab-caches-with-constructors"
              "0058-slub-extend-init_on_alloc-to-slab-caches-with-constructors"
              "0059-mm-add-support-for-verifying-page-sanitization"
              "0060-mm-slab-bug-on-page-type-confusion-under"
              "0061-bug-on-kmem_cache_free-with-the-wrong-cache"
              "0062-slub-bug-on-free-of-non-slab-objects"
              "0063-mm-kfence-bug-on-data-corruption-after-error-report"
              "0064-mm-slub-only-instrument-slab-allocation-with-canaries"
              "0065-take-slab-canary-in-account-for-object-size"
              "0066-security-perf-allow-further-restriction-of-perf_event_open"
              "0067-enable-security_perf_events_restrict-by-default"
              "0068-add-the-extra_latent_entropy-kernel-parameter"
              "0069-mm-fix-extra_latent_entropy"
              "0070-add-writable-function-pointer-detection"
              "0071-modpost-add-config_debug_writable_function_pointers_verbose"
              "0072-support-overriding-early-audit-kernel-cmdline"
              "0073-hard-wire-legacy-checkreqprot-option-to-0"
              "0074-security-tty-add-owner-user-namespace-to-tty_struct"
              "0075-security-tty-make-tiocsti-ioctl-require-cap_sys_admin"
              "0076-enable-security_tiocsti_restrict-by-default"
              "0077-enable-bpf-jit-hardening-by-default-if-available"
              "0078-enable-protected_-fifos-regular-by-default"
              "0079-sysctl-expose-proc_dointvec_minmax_sysadmin-as-api-function"
              "0080-sysctl-add-proc_dointvec_minmax_sysadmin-sanity-check"
              "0081-usb-implement-dedicated-subsystem-sysctl-tables"
              "0082-usb-add-toggle-for-disabling-newly-added-usb-devices"
              "0083-net-tcp-add-option-to-disable-tcp-simultaneous-connect"
              "0084-ovl-add-config-to-disable-unprivileged-user-namespace-mounts"
              "0085-restrict-device-timing-side-channels"
              "0086-io_uring-set-io_uring_disabled-sysctl-to-1-by-default"
              "0087-revert-mm-revert-x86_64-and-arm64-elf_et_dyn_base-base"
              "0088-x86-determine-stack-entropy-based-on-mmap-entropy"
              "0089-randomize-lower-bits-of-the-argument-block"
              "0090-support-randomizing-the-lower-bits-of-brk"
              "0091-mm-randomize-lower-bits-of-brk"
              "0092-x86-randomize-lower-bits-of-brk"
              "0093-mm-guarantee-brk-gap-is-at-least-one-page"
              "0094-x86-guarantee-brk-gap-is-at-least-one-page"
              "0095-ata-avoid-null-pointer-dereference-on-bug"
              "0096-sanity-check-for-negative-length-in-nla_memcpy"
              "0097-pax-shadow-cr4-sanity-check-essentially-a-revert"
              "0098-enable-ARM64_SW_TTBR0_PAN-by-default"
              "0099-arm64-enable-RANDOMIZE_BASE-by-default"
              "0100-remove-SYSVIPC-from-arm64-x86_64-defconfigs"
              "0101-arm64-determine-stack-entropy-based-on-mmap-entropy"
            ]
        ))
      )
      |> lib.sort lib.lessThan;
  };
}
