keys:
  - &main_machine age1st29vxtalmuzw4je4w3hfcnz8dtadcjf3ksx0742qv0lm5qf7pasw3w3pl
  - &vm_machine age1gzpr4f8nfrlfly7wy9rsyt8nlvh4yeefa5mh37eks4t0j04aq3nq90ld0w
  - &rogally_machine age1gz629hakxqlh9tqstw2w4rwehmwq034n36ntp58ljhuu8t7suenq68vrhr

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *main_machine
          - *vm_machine
          - *rogally_machine
