keys:
  - &main_machine age1st29vxtalmuzw4je4w3hfcnz8dtadcjf3ksx0742qv0lm5qf7pasw3w3pl
  - &vm_machine age1wfgtzn2qqjz9ktmfc82zqe70d5awjmtz779tgp5apw5r7quhc3nsje456y

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *main_machine
          - *vm_machine
