[
  "-d ACPI_DEBUG"
  "-d DEBUG_INFO_DWARF4"
  "-d DEBUG_INFO_DWARF5"
  "-d DEBUG_PREEMPT"
  "-d LATENCYTOP"
  "-d PAHOLE_HAS_SPLIT_BTF"
  "-d PAHOLE_HAS_SPLIT_BTF"
  "-d PM_ADVANCED_DEBUG"
  "-d PM_DEBUG"
  "-d PM_SLEEP_DEBUG"
  "-d SCHED_DEBUG"
  "-d SLUB_DEBUG"
]
