{ host }:
[
  "CONFIG_CACHY=y"
  "CONFIG_MQ_IOSCHED_ADIOS=y"
  "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=n"
  "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3=y"
  "CONFIG_LOCALVERSION_AUTO=n"
  "CONFIG_TRANSPARENT_HUGEPAGE_MADVISE=n"
  "CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS=y"
  "CONFIG_OVERLAY_FS=m"
  "CONFIG_OVERLAY_FS_REDIRECT_DIR=n"
  "CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y"
  "CONFIG_OVERLAY_FS_INDEX=n"
  "CONFIG_OVERLAY_FS_XINO_AUTO=n"
  "CONFIG_OVERLAY_FS_METACOPY=n"
  "CONFIG_OVERLAY_FS_DEBUG=n"
  "CONFIG_LLVM=y"
  "CONFIG_LLVM_IAS=y"
  "CONFIG_LTO_NONE=n"
  "CONFIG_LTO_CLANG_THIN=y"
  "CONFIG_LTO_CLANG_FULL=n"
  "CONFIG_NR_CPUS=320"
  "CONFIG_NTSYNC=m"

  "CONFIG_CONFIG_AUTOFS4_FS=y"
  "CONFIG_CONFIG_AUTOFS_FS=y"

  "CONFIG_PREEMPT_VOLUNTARY=n"
  "CONFIG_PREEMPT_LAZY=n"

  "CONFIG_LRU_GEN=y"
  "CONFIG_LRU_GEN_ENABLED=y"
  "CONFIG_LRU_GEN_STATS=n"

  "CONFIG_PER_VMA_LOCK=y"
  "CONFIG_PER_VMA_LOCK_STATS=n"

  "CONFIG_DEBUG_INFO=n"
  "CONFIG_DEBUG_INFO_BTF=n"
  "CONFIG_DEBUG_INFO_DWARF4=n"
  "CONFIG_DEBUG_INFO_DWARF5=n"
  "CONFIG_PAHOLE_HAS_SPLIT_BTF=n"
  "CONFIG_DEBUG_INFO_BTF_MODULES=n"
  "CONFIG_SLUB_DEBUG=n"
  "CONFIG_PM_DEBUG=n"
  "CONFIG_PM_ADVANCED_DEBUG=n"
  "CONFIG_PM_SLEEP_DEBUG=n"
  "CONFIG_ACPI_DEBUG=n"
  "CONFIG_SCHED_DEBUG=n"
  "CONFIG_LATENCYTOP=n"
  "CONFIG_DEBUG_PREEMPT=n"

  "CONFIG_BLK_DEV_NVME=y"
  "CONFIG_NLS=m"
  "CONFIG_NLS_UTF8=m"

  "CONFIG_VIRTIO=m"
  "CONFIG_VIRTIO_PCI=m"
  "CONFIG_VIRTIO_BLK=m"
  "CONFIG_VIRTIO_NET=m"

  "CONFIG_HZ_PERIODIC=n"
  "CONFIG_NO_HZ_COMMON=y"
  "CONFIG_NO_HZ=y"
]
++ (
  if host == "v7w7r-rc71l" then
    [
      "CONFIG_ASUS_ARMOURY=m"
      "CONFIG_AMD_PRIVATE_COLOR=y"
      "CONFIG_AMD_3D_VCACHE=m"
      "CONFIG_V4L2_LOOPBACK=m"
      "CONFIG_VHBA=m"
      "CONFIG_DRM_APPLETBDRM=m"
      "CONFIG_HID_APPLETB_BL=m"
      "CONFIG_HID_APPLETB_KBD=m"
      "CONFIG_# CONTEXT_TRACKING_FORCE is not set"
    ]
  else
    [ ]
)
++ (
  if host == "v7w7r-higole" || host == "v7w7r-youyeetoox1" then
    [
      "CONFIG_CONFIG_DEFAULT_FQ_CODEL=n"
      "CONFIG_CONFIG_DEFAULT_FQ=y"
      "CONFIG_DEFAULT_BBR=y"
      "CONFIG_DEFAULT_CUBIC=n"
      "CONFIG_DEFAULT_TCP_CONG=bbr"
      "CONFIG_NET_SCH_FQ_CODEL=m"
      "CONFIG_NET_SCH_FQ=y"
      "CONFIG_TCP_CONG_BBR=y"
      "CONFIG_TCP_CONG_CUBIC=m"
    ]
  else
    [ ]
)
++ (
  if host == "v7w7r-higole" then
    [
      "CONFIG_GENERIC_CPU=y"
      "CONFIG_MZEN4=n"
      "CONFIG_X86_NATIVE_CPU=n"
      "CONFIG_X86_64_VERSION=2"
    ]
  else
    [
      "CONFIG_GENERIC_CPU=n"
      "CONFIG_X86_NATIVE_CPU=y"
    ]
)
++ (
  if host == "v7w7r-youyeetoox1" then
    [
      "CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=n"
      "CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y"

      "CONFIG_PREEMPT_DYNAMIC=n"
      "CONFIG_PREEMPT=n"
      "CONFIG_PREEMPT_NONE=y"

      "CONFIG_HZ=300"
      "CONFIG_NO_HZ_IDLE=y"
      "CONFIG_NO_HZ_FULL=n"
    ]
  else
    [
      "CONFIG_SCHED_BORE=y"

      "CONFIG_PREEMPT_DYNAMIC=y"
      "CONFIG_PREEMPT=y"
      "CONFIG_PREEMPT_NONE=n"

      "CONFIG_CONTEXT_TRACKING_FORCE=n"
      "CONFIG_CONTEXT_TRACKING=y"
      "CONFIG_NO_HZ_FULL_NODEF=y"
      "CONFIG_NO_HZ_FULL=y"
    ]
)
