[
  "-e CACHY"
  "-e CONTEXT_TRACKING"
  "-e PREEMPT_BUILD"
  "-e PREEMPTION"
  #"-e SCHED_BORE"
  "-e SCHED_CLASS_EXT"
  "-e TRANSPARENT_HUGEPAGE_ALWAYS"

  "-m NTSYNC"

  "-d CONTEXT_TRACKING_FORCE"
  "-d PREEMPT_NONE"
  "-d TRANSPARENT_HUGEPAGE_MADVISE"
]
