[
  "--set-val HZ 300"
  "--set-val NR_CPUS 8"
  "--set-val SND_HDA_POWER_SAVE_DEFAULT 1"

  "-e CPU_FREQ_DEFAULT_GOV_POWERSAVE"
  "-e CPU_FREQ_GOV_CONSERVATIVE"
  "-e CPU_FREQ_GOV_ONDEMAND"
  "-e CPU_FREQ_GOV_POWERSAVE"
  "-e CPU_FREQ_GOV_SCHEDUTIL"
  "-e HZ_300"
  "-e NO_HZ_IDLE"
  "-e PCIEASPM_POWERSAVE"
  "-e PREEMPT_VOLUNTARY"
  "-e SND_HDA_POWER_SAVE"
  "-e USB_AUTOSUSPEND"

  "-d CPU_FREQ_DEFAULT_GOV_SCHEDUTIL"
  "-d CPU_FREQ_GOV_PERFORMANCE"
  "-d NO_HZ_FULL"
  "-d PREEMPT"
  "-d PREEMPT_DYNAMIC"
  "-d PREEMPTION"
]
