[
  "--set-val HZ 1000"
  "--set-val NR_CPUS 32"

  "-e CPU_FREQ_DEFAULT_GOV_SCHEDUTIL"
  "-e CPU_FREQ_GOV_CONSERVATIVE"
  "-e CPU_FREQ_GOV_ONDEMAND"
  "-e CPU_FREQ_GOV_PERFORMANCE"
  "-e CPU_FREQ_GOV_SCHEDUTIL"
  "-e HZ_1000"
  "-e NO_HZ_FULL"
  "-e NO_HZ_FULL_NODEF"
  "-e RCU_NOCB_CPU"
  "-e PREEMPT"
  "-e PREEMPT_COUNT"
  "-e PREEMPT_DYNAMIC"

  "-d NO_HZ_IDLE"
  "-d PREEMPT_VOLUNTARY"
]
